---
title: "CreditScoreRedPar"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(corrplot))
suppressMessages(library(GGally))
suppressMessages(library(expss))
suppressMessages(library(formattable))
suppressMessages(library(gridExtra))
```

Carga de archivos
```{r}
ruta <- "../Datos/"
archivo1 <- "german_credit_data.csv"
archivo2 <- "german.data"

GCdata <- as.data.frame(read.csv(paste0(ruta,archivo1)))
GCorginal <- as.data.frame(read.table(paste0(ruta,archivo2), sep = " ", header = F))

# eliminamos la 1ra columna de GCdata (indice)
GCdata <- GCdata[,-1]
# completando el GCdata con la variable de "Default" -> (1 = bueno, 2 = malo)
default <- GCorginal[,21]
GCdata$Default=default

# Resumen de variables (mismo orden de data frame)
# 1. Age (numeric)
# 2. Sex (text: male, female)
# 3. Job (numeric: 0 - unemployed, 1 - unskilled/resident, 2 - skilled, 3 - highly skilled)
# 4. Housing (text: own, rent, or free)
# 5. Saving accounts (text - little, moderate, quite rich, rich)
# 6. Checking account (numeric, in DM - Deutsch Mark)
# 7. Credit amount (numeric, in DM)
# 8. Duration (numeric, in month)
# 9. Purpose (text: car, furniture/equipment, radio/TV, domestic appliances, repairs, education, business, vacation/others) 
# 10. Default (1 - good, 2 - bad)

names(GCdata)[c(5,6,7)] <- c("Savings","Checking.Acc","C.Amount")
head(apply_labels(GCdata,
             Job = c("Unemployed" = 0, "Resident" = 1, "Skilled" = 2, "Officer" = 3),
             Default = c("Bueno" = 1, "Malo"=2)),10)
```

```{r}
library(dplyr)

#Hicimos Savings como factor para quitarle los NA's sin afectar la base de datos
# 0: Na 
# 1: little
#2: moderate
#3: quite rich
#4: rich

#Hicimos Checking account como factor para quitarle los NA's:
# 0: NA
# 1: little
#2: moderate
#3: rich


GCdata<-GCdata %>%
    mutate(Savings=ifelse(is.na(Savings),0, Savings)) %>%
    mutate(Checking.Acc= ifelse(is.na(Checking.Acc), 0, Checking.Acc))

GCdata$Savings<-factor(GCdata$Savings)
GCdata$Checking.Acc<-factor(GCdata$Checking.Acc)



head(GCdata,20)
```
```{r}
#Hicimos Age como factor donde 
# 1: age<50
# 2: age >=50
#lo hicimos así porque así venía en el paper del que nos estamos basando

GCdata<-GCdata %>%
  mutate(Age=ifelse(Age<50, 1 , 2))

GCdata$Age<-factor(GCdata$Age)

# convertimos job a factor
GCdata$Job<-factor(GCdata$Job)

head(GCdata,20)
```
```{r}
#convertimos el credit amount a factores:
# 1: C.Amount<1500
# 2: C.Amount 1500<x<2750
# 3: C.Amount 2750<x<4000
# 4: C.Amount>4000


GCdata<- GCdata %>%
  mutate(C.Amount=ifelse(C.Amount<1500, 1, ifelse(C.Amount<2750, 2, ifelse(C.Amount<4000, 3, 4))))

#lo convertimos a factor 
GCdata$C.Amount<-factor(GCdata$C.Amount)
head(GCdata,20)
```

```{r}
#Dividimos duration en 2 partes donde el parteaguas es la media:
# 1: Duration <21
# 2: Duration>21 
GCdata<-GCdata %>%
  mutate(Duration=ifelse(Duration<21, 1, 2))

GCdata$Duration<-factor(GCdata$Duration)

```

```{r}
#cambiamos default a factor

GCdata$Default<-factor(GCdata$Default)

head(GCdata, 10)
```

```{r}
#Ahora sí, empecemos con lo nuestro

library(deal)
```


```{r}
#No tenemos prior knowledge about specific dependency relations, so for simplicity we use the empty DAG as the prior DAG and let the probability distribution of the discrete variables be uniform

#specify prior network
GCdata_network<-network(GCdata)

#make joint prior distribution
GCdata_prior<-jointprior(GCdata_network)
#draw_net<-drawnetwork(GCdata_network, GCdata, GCdata_prior)

# learn the initial network
GCdata_network <- learn(GCdata_network,GCdata,GCdata_prior)$nw

# Do structural search
GCdata_search <- autosearch(GCdata_network,GCdata,GCdata_prior,trace=TRUE)

## perturb ’thebest’ and rerun search twice.
GCdata_heuristic <- heuristic(GCdata_search$nw,GCdata, GCdata_prior,restart=2,degree=10,
trace=TRUE,trylist=GCdata_search$trylist)

thebestGC<- GCdata_heuristic$nw

```

```{r}
savenet(thebest2, con=file("GCdata.net"))
```
```{r}
data(ksl) ## read data (included in DEAL)
## specify prior network
ksl.nw <- network(ksl)
## make joint prior distribution
ksl.prior <- jointprior(ksl.nw)
## ban arrows towards Sex and Year
mybanlist <- matrix(c(5,5,6,6,7,7,9,
8,9,8,9,8,9,8),ncol=2)
banlist(ksl.nw) <- mybanlist

## learn the initial network
ksl.nw <- learn(ksl.nw,ksl,ksl.prior)$nw
## Do structural search
ksl.search <- autosearch(ksl.nw,ksl,ksl.prior,trace=TRUE)
## perturb ’thebest’ and rerun search twice.
ksl.heuristic <- heuristic(ksl.search$nw,ksl,
ksl.prior,
restart=2,degree=10,
trace=TRUE,trylist=ksl.search$trylist)
thebest2 <- ksl.heuristic$nw
savenet(thebest2, con=file("ksl.net"))

```
```{r}
library(bnlearn)
```

```{r}

GCprueba2 <- hc(GCdata, score = "k2")
GCprueba2

plot(GCprueba2, main="Bayesian Network Credit Score")
```

